[workspace]
members = ["day-1", "day-2", "day-3", "day-4", "day-5", "day-6", "day-7", "day-8", "day-9"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
